=pod

=encoding UTF-8

=head1 NAME

Qanu::API::PyTextRank - Provides access to PyTextRank

=head1 VERSION

version 0.001

=head1 METHODS

=head2 get_text_rank

Returns the PyTextRank data for a given document.

=head1 SEE ALSO

=head1 AUTHOR

Zakariyya Mughal <zmughal@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018 by Zakariyya Mughal.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
